<%@ Register TagPrefix="def" Namespace="DataEntryFramework3" %> 
<%@ Page language="c#" MasterPageFile="~/UWAC.master"  Title="SIT Data Entry" %>
<asp:Content ID="Content2" ContentPlaceHolderID="oBodyPlaceHolder" runat="server">

<link rel="stylesheet" type="text/css" href="/research/dataentry/dataentryform.css" />
<def:dataentrycontroller id="dataentrycontroller1" runat="server" databasetable="ALL_SIT" primarykeyfield="sit_pk">
</def:dataentrycontroller>
   <asp:scriptmanager id="scriptmanager1" runat="server">    </asp:scriptmanager>
<asp:updatepanel id="updatepanel1" runat="server">
  <contenttemplate>
<table>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="id" databasefield="id" isinsertfield="true" fieldlabelwidth="300px" fieldtextboxwidth="250px" fieldtextboxmaxlength="15"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="indexnum" databasefield="indexnum" isinsertfield="true" fieldtextboxtextdefault="1" fieldlabelwidth="300px" fieldtextboxwidth="40px"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_date" databasefield="sit_date" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="300px" formatstring="{0:d}" ></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_agemo" databasefield="sit_agemo" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" fieldtextboxwidth="40px"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_exmnr" databasefield="sit_exmnr" isentryfield="true" isdoubleentryfield="false" fieldlabelwidth="300px" fieldtextboxwidth="250px" fieldtextboxmaxlength="20"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_resp" databasefield="sit_resp" isentryfield="true" isdoubleentryfield="false" fieldlabelwidth="300px" fieldtextboxwidth="250px" fieldtextboxmaxlength="50"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_cmnt" databasefield="sit_cmnt" isentryfield="true" isdoubleentryfield="false" fieldlabelwidth="300px" fieldtextboxwidth="400px" fieldtextboxheight="40px" fieldtextboxtextmode="multiline" fieldtextboxmaxlength="250"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_scrmsg" databasefield="sit_scrmsg" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" fieldtextboxwidth="400px" fieldtextboxheight="40px" fieldtextboxtextmode="multiline" fieldtextboxmaxlength="250"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_tot" databasefield="sit_tot"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" fieldtextboxwidth="40px"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit_pct" databasefield="sit_pct"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" fieldtextboxwidth="40px" FormatString="{0:p}"></def:datafieldcontrol></td>
<td></td></tr>
  </table>
      <br />
      <asp:Label ID="Label1" runat="server" Text="Enter response for each item (a,c,b,d)"></asp:Label>
      <br />
<table>
    <tr><td align="right"><b><u>Enter Item</u></b></td>
        <td align="right" width="100px"><b><u>Pass=1, Fail=0</u></b></td>
    </tr>
    <tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit01" databasefield="sit01" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF01" databasefield="sitPF01"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit02" databasefield="sit02" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF02" databasefield="sitPF02"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit03" databasefield="sit03" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF03" databasefield="sitPF03"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit04" databasefield="sit04" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF04" databasefield="sitPF04"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit05" databasefield="sit05" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF05" databasefield="sitPF05"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit06" databasefield="sit06" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF06" databasefield="sitPF06"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit07" databasefield="sit07" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF07" databasefield="sitPF07"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit08" databasefield="sit08" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF08" databasefield="sitPF08"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit09" databasefield="sit09" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF09" databasefield="sitPF09"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit10" databasefield="sit10" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF10" databasefield="sitPF10"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit11" databasefield="sit11" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF11" databasefield="sitPF11"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit12" databasefield="sit12" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF12" databasefield="sitPF12"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit13" databasefield="sit13" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF13" databasefield="sitPF13"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit14" databasefield="sit14" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF14" databasefield="sitPF14"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit15" databasefield="sit15" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF15" databasefield="sitPF15"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit16" databasefield="sit16" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF16" databasefield="sitPF16"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit17" databasefield="sit17" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF17" databasefield="sitPF17"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit18" databasefield="sit18" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF18" databasefield="sitPF18"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit19" databasefield="sit19" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF19" databasefield="sitPF19"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit20" databasefield="sit20" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF20" databasefield="sitPF20"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit21" databasefield="sit21" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF21" databasefield="sitPF21"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit22" databasefield="sit22" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF22" databasefield="sitPF22"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit23" databasefield="sit23" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF23" databasefield="sitPF23"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit24" databasefield="sit24" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF24" databasefield="sitPF24"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit25" databasefield="sit25" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF25" databasefield="sitPF25"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit26" databasefield="sit26" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF26" databasefield="sitPF26"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit27" databasefield="sit27" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF27" databasefield="sitPF27"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit28" databasefield="sit28" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF28" databasefield="sitPF28"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit29" databasefield="sit29" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF29" databasefield="sitPF29"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit30" databasefield="sit30" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF30" databasefield="sitPF30"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit31" databasefield="sit31" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF31" databasefield="sitPF31"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit32" databasefield="sit32" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF32" databasefield="sitPF32"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit33" databasefield="sit33" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF33" databasefield="sitPF33"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit34" databasefield="sit34" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF34" databasefield="sitPF34"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit35" databasefield="sit35" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF35" databasefield="sitPF35"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit36" databasefield="sit36" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF36" databasefield="sitPF36"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit37" databasefield="sit37" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF37" databasefield="sitPF37"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit38" databasefield="sit38" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF38" databasefield="sitPF38"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit39" databasefield="sit39" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF39" databasefield="sitPF39"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sit40" databasefield="sit40" isentryfield="true" isdoubleentryfield="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="sitPF40" databasefield="sitPF40"  isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="50px" fieldtextboxwidth="40px"></def:datafieldcontrol></td></tr>

</table>

      <br />
      <br />

      <table>
<br/><br/><tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="created" databasefield="created" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="createdby" databasefield="createdby" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" fieldtextboxwidth="250px" fieldtextboxmaxlength="50"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="updated" databasefield="updated" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" formatstring="{0:d}" ></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="updatedby" databasefield="updatedby" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" fieldtextboxwidth="250px" fieldtextboxmaxlength="50"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="scored" databasefield="scored" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px"></def:datafieldcontrol></td>
<td></td></tr>
 
<tr><td style="vertical-align:top"><def:datafieldcontrol runat="server" id="scoredby" databasefield="scoredby" isreadonly="true" renderreadonlyasdiv="true" fieldlabelwidth="300px" fieldtextboxwidth="250px" fieldtextboxmaxlength="50"></def:datafieldcontrol></td>
<td></td></tr>
 
</table>
</contenttemplate>
<triggers></triggers>
</asp:updatepanel>
</asp:content>
